#!/bin/sh
# Don't believe the warning below: this is the file you want to edit

echo "# Do not edit this file, it's generated from a template. Instead, edit"
echo "# $PWD/shell/alias.tmpl.sh in dotfiles/shell"
echo ""

try_override () {
  if which $2 >/dev/null 2>&1; then
    eval "$1='$2'"
    echo "alias $1='$2'"
  else
    ls='ls'
  fi
}

try_override  sed   gsed
try_override  grep  ggrep
try_override  cat   bat
try_override  ls    exa
try_override  vim   nvim

cat << EOF

alias f='pop-mark'
alias m='mark-dir'

alias lass='$ls -lahg --color=always | less -R'
alias arst='asdf'
alias ncdu="ncdu --color dark -rr -x"
# alias ncdu="ncdu --color dark -rr -x --exclude .git --exclude node_modules"
alias nim="nim --outdir:$HOME/.nimble/_out"
alias kak="kak -c default"

alias fim='f=\`fd . -t f | fzy\` && vim \$f' # use fzf to select a file but only open on return 1

# shortcut commands
alias g='git'
alias la='$ls -lahg'
alias v='vagrant'
alias rr='ranger'
alias sx='startx;exit'
alias up='cd ..'
alias fab=comfortable-fab
alias nm1=notmuch-primary
alias nm2=notmuch-secondary

# unglob some commands
alias fd='noglob fd'
alias fdi='noglob fd -I'
alias rg='noglob rg'
alias w3m='noglob w3m'
alias jq='noglob jq'
alias yq='noglob yq'

EOF
exit 0
