#!/usr/bin/bash
#xorg configs
ln -sf "$PWD/xinitrc" ~/.xinitrc
ln -sf "$PWD/xsession" ~/.xsession
ln -sf "$PWD/xres" ~/.xres

#vim configs
ln -sf "$PWD/vimrc" ~/.vimrc
mkdir ~/.vim
ln -sf $PWD/bundle ~/.vim/bundle
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

#tmux config
ln -sf "$PWD/tmux.conf" ~/.tmux.conf

#zsh configs
ln -sf $PWD/zshrc ~/.zshrc
mkdir ~/.zfunctions
fpath=( "$HOME/.zfunctions" $fpath )
ln -sf "$PWD/pure.zsh" "$HOME/.zfunctions/prompt_pure_setup"
ln -sf "$PWD/async.zsh" "$HOME/.zfunctions/async"

# i3 config
mkdir -p ~/.config/i3
ln -sf "$PWD/i3_config" ~/.config/i3/config
