#!/bin/bash
if [[ ! -f "./setup" ]]; then
  echo "This script must be run from the directory it's contained in"
  exit
fi

while [ $1 ]; do
  case "$1" in
    "uninstall") uninstall=true;shift;;
    "-r"|"--remove-backups") remove_backups=true;shift;;
    "-f"|"--force-overwrite") force_overwrite=true;shift;;
    "-n"|"--nobuild-templates") nobuild_templates=true;shift;;
    "-h"|"--help")
      echo "Command line arguments:"
      echo "  -r   --remove-backups     Remove old .bak files from safe copy"
      echo "  -f   --force-overwrite    Force overwrite of copied files"
      echo "  -n   --nobuild-templates  Don't rebuild .tmpl.sh files"
      exit;;
    *) echo "Unknown command line option $1";exit;;
  esac
done

echo "Sourcing profile and user-profile to make sure we have the latest env..."
source $PWD/profile
source $PWD/user-profile

build_template () {
  if [ ! $nobuild_templates ]; then
    [ -f "$1.tmpl.sh" ] || echo "        Template $1.tmpl.sh not found, skipping. Please fix this!"
    sh "$1.tmpl.sh" > "$1"
  fi
}

symlink () {
  if [ $uninstall ]; then
    [ -L $3 ] && rm $3
    return 0
  fi

  case "$1" in
    dir)
      [ -L $3 ] && rm $3
      ln -s $2 $3
      ;;
    file)
      ln -sf $2 $3
      ;;
  esac
}

# safe copy function that only updates changed files, and takes a backup of changes
safe_copy () {
  # just copy and overwrite if force_overwrite is on
  [ $force_overwrite ] && cat $1 > $2 && return 0
  which shasum >/dev/null 2>/dev/null && hash_command='shasum'
  hash_new=`$hash_command $1 | head -c 40`
  hash_old=`$hash_command $2 | head -c 40`
  if [[ $hash_new = $hash_old ]]; then
    echo "    $2 hasn't changed, skipping..."
  else
    [ -f "$2.bak" ] && \
      "$2.bak would be overwritten, please move or delete that file to prevent data loss" && return 1
    [ ! $remove_backups ] && \
      [ -f $2 ] && \
      mv $2 "$2.bak"
    [ $remove_backups ] && rm "$2.bak"
    cp "$1" "$2"
  fi
}

# load git submodules
git submodule update zmodules/zsh-syntax-highlighting

echo "Building shell template files"
build_template $PWD/gpg/gpg.conf
build_template $PWD/gpg/gpg-agent.conf
build_template $PWD/gitconfig
build_template $PWD/README.md
build_template $PWD/neomuttrc-user
build_template $PWD/nvim/pathspec.vim

echo "Making the config directory and linking/copying files"
mkdir -p ~/.config/

echo "  Xorg configs"
symlink file "$PWD/xinitrc" ~/.xinitrc
symlink file "$PWD/xsession" ~/.xsession
symlink dir "$PWD/xres" ~/.xres

echo "  Urxvt conf"
mkdir -p ~/.urxvt
symlink dir "$PWD/urxvt-ext" ~/.urxvt/ext

# using vim as a more lightweight editor atm, nvim as a full editor
echo "  Vim directories and conf"
symlink file "$PWD/vimrc" ~/.vimrc
mkdir -p ~/.vim
mkdir -p ~/.vim/blugin
mkdir -p ~/.vim/autoload
mkdir -p ~/.vim/files
mkdir -p ~/.vim/files/swap
mkdir -p ~/.vim/files/backup
mkdir -p ~/.vim/files/info
mkdir -p ~/.vim/files/undo
symlink file "$PWD/plug.vim" ~/.vim/autoload/plug.vim

echo "  Neovim conf"
mkdir -p ~/.config
mkdir -p ~/.local/share/nvim/site/autoload
mkdir -p ~/.local/share/nvim
mkdir -p ~/.local/share/nvim/blugin
mkdir -p ~/.local/share/nvim/autoload
mkdir -p ~/.local/share/nvim/files
mkdir -p ~/.local/share/nvim/files/swap
mkdir -p ~/.local/share/nvim/files/backup
mkdir -p ~/.local/share/nvim/files/info
mkdir -p ~/.local/share/nvim/files/undo
symlink dir "$PWD/nvim" ~/.config/nvim
symlink file "$PWD/plug.vim" ~/.local/share/nvim/site/autoload/plug.vim

echo "  GPG config"
mkdir -p ~/.gnupg
safe_copy "$PWD/gpg/gpg.conf" ~/.gnupg/gpg.conf
safe_copy "$PWD/gpg/gpg-agent.conf" ~/.gnupg/gpg-agent.conf
mkdir -p ~/.ssh
safe_copy "$PWD/ssh_config" ~/.ssh/config
touch ~/.ssh/user_config

echo "  Tmux config"
symlink file "$PWD/tmux.conf" ~/.tmux.conf
symlink file "$PWD/tmux-disposable.conf" ~/.tmux-disposable.conf

echo "  Zsh configs"
symlink file $PWD/zshrc ~/.zshrc
symlink dir $PWD/zfunctions ~/.zfunctions
symlink dir $PWD/zmodules ~/.zmodules

echo "  Qutebrowser config"
symlink dir "$PWD/qutebrowser" ~/.config/qutebrowser

echo "  i3 config"
mkdir -p ~/.config/i3
symlink file "$PWD/i3_config" ~/.config/i3/config

echo "  Email config"
symlink file "$PWD/neomuttrc-user" ~/.neomuttrc-user
symlink file "$PWD/neomuttrc-unbind" ~/.neomuttrc-unbind
symlink file "$PWD/neomuttrc" ~/.neomuttrc
symlink file "$PWD/notmuch-config" ~/.notmuch-config
mkdir -p ~/email/work

echo "  Ranger config"
mkdir -p ~/.config/ranger
symlink file "$PWD/rifle.conf" ~/.config/ranger/rifle.conf
symlink file "$PWD/rc.conf" ~/.config/ranger/rc.conf

echo "  Other configs"
symlink file "$PWD/spacemacs" ~/.spacemacs
symlink file "$PWD/batrc" ~/.batrc
symlink file "$PWD/alias" ~/.alias
symlink file "$PWD/profile" ~/.profile
symlink file "$PWD/user-profile" ~/.user-profile
symlink file "$PWD/tmux.conf" ~/.tmux.conf
symlink file "$PWD/compton.conf" ~/.config/compton.conf
symlink file "$PWD/editorconfig" ~/.editorconfig
symlink file "$PWD/gitconfig" ~/.gitconfig
symlink file "$PWD/tigrc" ~/.tigrc
symlink file "$PWD/ctags" ~/.ctags

echo "  Symlinking directories"
#TODO make this check for an existing bin dir
symlink dir "$PWD/bin" ~/.bin
symlink dir "$PWD/emacs.d" ~/.emacs.d

echo "  Making the ~/.local/bin directory"
mkdir -p ~/.local/bin

echo "...Finished!"
