#!/bin/sh
mkdir -p ~/.config/

#xorg configs
ln -sf "$PWD/xinitrc" ~/.xinitrc
ln -sf "$PWD/xsession" ~/.xsession
rm ~/.xres
ln -s "$PWD/xres" ~/.xres

# urxvt conf
mkdir -p ~/.urxvt
rm ~/.urxvt/ext
ln -s "$PWD/urxvt-ext" ~/.urxvt/ext

#vim directories and conf
ln -sf "$PWD/vimrc" ~/.vimrc
mkdir -p ~/.vim
mkdir -p ~/.vim/blugin
mkdir -p ~/.vim/autoload
mkdir -p ~/.vim/files
mkdir -p ~/.vim/files/swap
mkdir -p ~/.vim/files/backup
mkdir -p ~/.vim/files/info
mkdir -p ~/.vim/files/undo
ln -sf "$PWD/plug.vim" ~/.vim/autoload/plug.vim

#tmux config
ln -sf "$PWD/tmux.conf" ~/.tmux.conf

#zsh configs
ln -sf "$PWD/antigen.zsh" ~/antigen.zsh
rm -rf ~/.antigen
ln -sf $PWD/zshrc ~/.zshrc
rm ~/.zfunctions
ln -s $PWD/zfunctions ~/.zfunctions

# qutebrowser config
rm ~/.config/qutebrowser
ln -s "$PWD/qutebrowser" ~/.config/qutebrowser

# i3 config
mkdir -p ~/.config/i3
ln -sf "$PWD/i3_config" ~/.config/i3/config

# ranger config
mkdir -p ~/.config/ranger
ln -sf "$PWD/rifle.conf" ~/.config/ranger/rifle.conf
ln -sf "$PWD/rc.conf" ~/.config/ranger/rc.conf

# various configs
ln -sf "$PWD/spacemacs" ~/.spacemacs
ln -sf "$PWD/batrc" ~/.batrc
ln -sf "$PWD/alias" ~/.alias
ln -sf "$PWD/profile" ~/.profile
ln -sf "$PWD/tmux.conf" ~/.tmux.conf
ln -sf "$PWD/compton.conf" ~/.config/compton.conf

# various directories
rm ~/.bin || echo '~/.bin should be a symlink, if it is a directory, please migrate the old files to local or remove it'
ln -s "$PWD/bin" ~/.bin

mkdir -p ~/.local/bin
