#!/bin/sh

# Uncomment the terminal color scheme you want to use
# xrdb colors-material
# xrdb colors-onedark
xrdb colors-onedark-vibrant
# xrdb colors-faded
# xrdb colors-zenburn
# xrdb colors-dracula

xrdb -merge xresources-rofi
xrdb -merge xresources-urxvt
