# vim: fileencoding=utf-8:ft=kitty.conf:foldmethod=marker

include colors.conf

font_size 15.0

scrollback_lines 0

term xterm-256color

macos_option_as_alt yes

kitty_mod super+ctrl+shift

map kitty_mod+j kitten hints --customize-processing hints-jira.py
map kitty_mod+u kitten hints --customize-processing hints-yank.py
map kitty_mod+o kitten kitten-decode-uuid.py
map kitty_mod+e kitten hints

map kitty_mod+f7 set_colors ~/.config/kitty/colors.conf
map kitty_mod+f8 set_colors ~/.config/kitty/colors-light.conf
enable_audio_bell no


# BEGIN_KITTY_FONTS
font_family      family='Iosevka Fixed' postscript_name=Iosevka-Fixed
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
